package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/yowainwright/shellcheck_legibility/internal/app"
	"github.com/yowainwright/shellcheck_legibility/internal/lint"
)

type ruleFixture struct{ code, path, source string }

func TestEveryRuleMatchesBash(t *testing.T) {
	enterTestWorkspace(t)
	fixtures := append(controlFixtures(), shellFixtures()...)
	for _, fixture := range fixtures {
		t.Run(fixture.code, func(t *testing.T) { compareRule(t, fixture) })
	}
}

func controlFixtures() []ruleFixture {
	return []ruleFixture{
		{"LEG001", "example.sh", "build && test && package && publish && notify && finish\n"},
		{"LEG002", "example.sh", "if ready && online; then work; fi\n"},
		{"LEG003", "example.sh", "if a; then\nif b; then\nif c; then\nif d; then work; fi\nfi\nfi\nfi\n"},
		{"LEG005", "example.sh", "for a in one; do\nfor b in two; do work; done\ndone\n"},
		{"LEG009", "example.sh", "run() {\nif ready; then\nreturn\nelse\nwork\nfi\n}\n"},
		{"LEG010", "example.sh", "run() {\nif ready; then\nwork\nfi\n}\n"},
	}
}

func shellFixtures() []ruleFixture {
	return []ruleFixture{
		{"LEG016", "scripts/run.sh", "run() { :; }\n"},
		{"LEG017", "example.sh", "bash scripts/run.sh\n"},
		{"LEG024", "example.sh", "if [[ $mode == a || $mode == b || $mode == c ]]; then work; fi\n"},
		{"LEG025", "src/forms/button/other.sh", "run() { :; }\n"},
		{"LEG026", "mixed_Name.sh", "run() { :; }\n"},
		{"LEG034", "example.sh", "if [[ $mode == a ]]; then work\nelif [[ $mode == b ]]; then work\nelif [[ $mode == c ]]; then work\nfi\n"},
		{"LEG035", "example.sh", "create_user true\n"},
		{"LEG038", "example.sh", "run() {\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nwork\n}\n"},
		{"LEG039", "example.sh", "docker build .\n"},
		{"LEG040", "example.sh", "run() {\nlocal name=$1\n}\n"},
		{"LEG041", "example.sh", "# ordinary comment\n"},
		{"LEG042", "example.sh", "# Generated by Codex.\n"},
		{"LEG043", "example.sh", "# first comment\n# second comment\n"},
	}
}

func compareRule(t *testing.T, fixture ruleFixture) {
	writeRuleFixture(t, fixture)
	options := app.Options{Select: fixture.code}
	expected, err := legacyScan(fixture.path, options)
	if err != nil {
		t.Fatal(err)
	}
	config := lint.DefaultConfig()
	config.Select = []string{fixture.code}
	actual, err := lint.Scan(fixture.path, []byte(fixture.source), config)
	if err != nil {
		t.Fatal(err)
	}
	if len(expected) == 0 {
		t.Fatal("fixture did not exercise the rule")
	}
	compareRuleJSON(t, expected, actual)
}

func writeRuleFixture(t *testing.T, fixture ruleFixture) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(fixture.path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fixture.path, []byte(fixture.source), 0600); err != nil {
		t.Fatal(err)
	}
}

func compareRuleJSON(t *testing.T, expected, actual []lint.Diagnostic) {
	t.Helper()
	expectJSON, _ := json.Marshal(expected)
	actualJSON, _ := json.Marshal(actual)
	if string(expectJSON) != string(actualJSON) {
		t.Fatalf("expected %s\nactual   %s", expectJSON, actualJSON)
	}
}

func TestIncompleteShellKeepsFeedbackWithoutExecutingSource(t *testing.T) {
	enterTestWorkspace(t)
	source := "touch executed\nrun() { create_user true;\n"
	if err := os.WriteFile("incomplete.sh", []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	findings, err := legacyScan("incomplete.sh", app.Options{Select: "LEG035"})
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].Code != "LEG035" {
		t.Fatalf("findings: %+v", findings)
	}
	if _, err := os.Stat("executed"); !os.IsNotExist(err) {
		t.Fatal("scanned source was executed")
	}
}

func TestMissingBashReportsAnError(t *testing.T) {
	t.Setenv("PATH", "")
	_, err := legacyScan("incomplete.sh", app.Options{})
	if err == nil {
		t.Fatal("missing Bash did not return an error")
	}
}

func enterTestWorkspace(t *testing.T) {
	t.Helper()
	if err := os.MkdirAll(".build", 0755); err != nil {
		t.Fatal(err)
	}
	dir, err := os.MkdirTemp(".build", "native-test-")
	if err != nil {
		t.Fatal(err)
	}
	absolute, err := filepath.Abs(dir)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(absolute) })
	t.Chdir(absolute)
}
