package lint

import "testing"

func TestCommentRuleNamesSelectExplicitly(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"no-unmatched-comments"}
	source := `


# explain this branch
`
	want := []expectedDiagnostic{
		{"LEG041", 4, 1, "Comment does not match a configured matcher, prefix identifier, or suffix identifier."},
	}
	assertScan(t, source, config, want)
}

func TestCommentRulesAreOptIn(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"all"}
	source := `


# explain this branch
# Generated by codex.
# First comment.
# Second comment.
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttribution(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoAutomatedCommentAttributionAllowsEmptyIdentifiers(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	config.AutomatedIdentifiers = []string{}
	source := `


# Generated by codex.
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttributionAllowsMidPhraseIdentifiers(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Written by an ai engineer.
# Generated by ai-assisted tooling.
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttributionAllowsReferences(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Send the request to OpenAI.
# Parse the AI response.
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttributionDetectsArticleSignature(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Generated by an ai.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"ai\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoAutomatedCommentAttributionDetectsAuthor(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# @AUTHOR: openai
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"openai\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoAutomatedCommentAttributionDetectsConjunction(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Generated by codex and reviewed by Alice.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoAutomatedCommentAttributionDetectsTrailingProse(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `


# Generated by codex; do not edit.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoAutomatedCommentAttributionIgnoresDirectives(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `#!/usr/bin/env bash
# shellcheck disable=SC1091
# noqa: LEG042
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttributionSupportsCustomIdentifiers(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	config.AutomatedIdentifiers = []string{"robot"}
	source := `


# robot-authored.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"robot\"."},
	}
	assertScan(t, source, config, want)
}

func TestNoStackedComments(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `# First comment.
# Second comment.
`
	want := []expectedDiagnostic{
		{"LEG043", 2, 1, "Update or remove the adjacent comment instead of stacking another comment."},
	}
	assertScan(t, source, config, want)
}

func TestNoStackedCommentsAllowsSeparation(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `# First comment.

# Second comment.
printf '%s\n' value
# Third comment.
`
	assertScan(t, source, config, nil)
}

func TestNoStackedCommentsIgnoresDirectives(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `#!/usr/bin/env bash
# shellcheck disable=SC1091
# noqa: LEG043
# First comment.
`
	assertScan(t, source, config, nil)
}

func TestNoStackedCommentsRespectsInlineNoqa(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := "# First comment.\n# Second comment. noqa: LEG043\n"
	assertScan(t, source, config, nil)
}

func TestNoStackedCommentsIgnoresNonComments(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `printf '%s\n' '# Quoted.'
# First comment.
cat <<'EOF'
# Heredoc payload.
EOF
# Second comment.
`
	assertScan(t, source, config, nil)
}

func TestNoStackedCommentsReportsEachAddition(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `# First comment.
# Second comment.
# Third comment.
`
	want := []expectedDiagnostic{
		{"LEG043", 2, 1, "Update or remove the adjacent comment instead of stacking another comment."},
		{"LEG043", 3, 1, "Update or remove the adjacent comment instead of stacking another comment."},
	}
	assertScan(t, source, config, want)
}

func TestNoStackedCommentsRuleFunction(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG043"}
	source := `# First comment.
# Second comment.
`
	want := []expectedDiagnostic{
		{"LEG043", 2, 1, "Update or remove the adjacent comment instead of stacking another comment."},
	}
	assertScan(t, source, config, want)
}

func TestNoStackedCommentsSelectsByName(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"no-stacked-comments"}
	source := `# First comment.
# Second comment.
`
	want := []expectedDiagnostic{
		{"LEG043", 2, 1, "Update or remove the adjacent comment instead of stacking another comment."},
	}
	assertScan(t, source, config, want)
}

func TestNoUnmatchedComments(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	source := `


# explain this branch
`
	want := []expectedDiagnostic{
		{"LEG041", 4, 1, "Comment does not match a configured matcher, prefix identifier, or suffix identifier."},
	}
	assertScan(t, source, config, want)
}

func TestNoUnmatchedCommentsAllowsExactSuffixIdentifier(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	config.CommentSuffixes = []string{"@keep"}
	source := `


# @keep
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsAllowsMatcher(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	config.CommentMatchers = []string{"ENG-[0-9]+"}
	source := `


# ENG-482 tracks this branch
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsAllowsPrefixIdentifier(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	config.CommentPrefixes = []string{"KEEP"}
	source := `


# KEEP: legacy API order
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsAllowsSuffixIdentifier(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	config.CommentSuffixes = []string{"@keep"}
	source := `


deploy "$target" # preserve order @keep
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsIgnoresDirectives(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	source := `#!/usr/bin/env bash
# shellcheck disable=SC1091
# noqa: LEG041
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsRejectsPartialIdentifiers(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	config.CommentPrefixes = []string{"KEEP"}
	config.CommentSuffixes = []string{"@keep"}
	source := `


# KEEPING generated not@keep
`
	want := []expectedDiagnostic{
		{"LEG041", 4, 1, "Comment does not match a configured matcher, prefix identifier, or suffix identifier."},
	}
	assertScan(t, source, config, want)
}
