package lint

import (
	"slices"
	"testing"
)

type expectedDiagnostic struct {
	code         string
	line, column int
	message      string
}

func assertScan(t *testing.T, source string, config Config, want []expectedDiagnostic) {
	t.Helper()
	findings, err := Scan("example.sh", []byte(source), config)
	if err != nil {
		t.Fatal(err)
	}
	var got []expectedDiagnostic
	for _, diagnostic := range findings {
		if diagnostic.Path != "example.sh" {
			t.Errorf("path: %q", diagnostic.Path)
		}
		got = append(got, expectedDiagnostic{diagnostic.Code, diagnostic.Line, diagnostic.Column, diagnostic.Message})
	}
	if !slices.Equal(got, want) {
		t.Fatalf("expected: %+v\nactual: %+v", want, got)
	}
}

func TestBoolAfterQuotedArgReported(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG035"}
	source := `create_user "$name" false
`
	want := []expectedDiagnostic{
		{"LEG035", 1, 1, "Avoid boolean literal arguments. Name the option before passing it."},
	}
	assertScan(t, source, config, want)
}

func TestCasePatternsAreNotPipelines(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG001", "LEG035"}
	config.MaxExpression = 0
	source := `case "$answer" in
true | false | yes | no)
work ;;
esac
`
	assertScan(t, source, config, nil)
}

func TestEscapedQuotesKeepLiteralArguments(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG035"}
	source := `run() {
printf "%s\n" "escaped \" true" false
printf '%s\n' $'can\'t true' false
}
`
	want := []expectedDiagnostic{
		{"LEG035", 2, 1, "Avoid boolean literal arguments. Name the option before passing it."},
		{"LEG035", 3, 1, "Avoid boolean literal arguments. Name the option before passing it."},
	}
	assertScan(t, source, config, want)
}

func TestHeredocFunctionLinesPreserved(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG038"}
	config.MaxFunction = 4
	source := `write() {
cat <<'EOF'
data
}
more data
EOF
}
`
	want := []expectedDiagnostic{
		{"LEG038", 1, 1, "Function has 7 lines (max 4). Extract focused helper functions."},
	}
	assertScan(t, source, config, want)
}

func TestHeredocIsNotShellSyntax(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG001", "LEG002", "LEG035"}
	config.MaxExpression = 0
	source := `write() {
cat <<'EOF'
true false || &&
}
if data; then
EOF
}
`
	assertScan(t, source, config, nil)
}

func TestLiteralOperatorsAllowed(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG001", "LEG002"}
	config.MaxExpression = 0
	source := `if grep -q "a || b && c" file; then
work
fi
`
	assertScan(t, source, config, nil)
}

func TestMultilineLiteralIsNotShellCode(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG001", "LEG002", "LEG035"}
	source := `run() {
node -e '
if (ready && true) {
return false;
}
'
}
`
	assertScan(t, source, config, nil)
}

func TestNoAutomatedCommentAttributionSkipsQuotedHashes(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `





printf '%s\n' '# Generated by codex.'
`
	assertScan(t, source, config, nil)
}

func TestNoUnmatchedCommentsSkipsQuotedHashes(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041"}
	source := `





printf '%s\n' '#!/usr/bin/env bash'
`
	assertScan(t, source, config, nil)
}

func TestActivatesHeredocAfterBlankContinuation(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `cat <<EOF \

# Generated by codex.
EOF
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 5, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestClosesEscapedHeredoc(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `cat <<\EOF
# Generated by codex.
EOF
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestClosesQuotedHeredocWithSpaces(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `cat <<'END MARK'
# Generated by codex.
END MARK
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestDefersHeredocAcrossContinuation(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `cat <<EOF \
# Generated by codex.
# Generated by codex.
EOF
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 2, 1, "Comment contains the prohibited attribution \"codex\"."},
		{"LEG042", 5, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestDetectsCommentInBacktickSubstitution(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := "value=\"`printf ok\n# Generated by codex.\n`\"\n"
	want := []expectedDiagnostic{
		{"LEG042", 2, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestDetectsQuotedCommandSubstitutionHeredoc(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `value="$(cat <<'EOF'
# Generated by codex.
EOF
)"
`
	assertScan(t, source, config, nil)
}

func TestPreservesMultilineQuoteState(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG042"}
	source := `value="first line
# Generated by codex.
last line"
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
	}
	assertScan(t, source, config, want)
}

func TestRunsCommentPolicy(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041", "LEG042"}
	source := `


# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 4, 1, "Comment contains the prohibited attribution \"codex\"."},
		{"LEG041", 4, 1, "Comment does not match a configured matcher, prefix identifier, or suffix identifier."},
	}
	assertScan(t, source, config, want)
}

func TestSkipsAnsiCQuotedHash(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041", "LEG042"}
	source := `value=$'can\'t # Generated by codex.'
`
	assertScan(t, source, config, nil)
}

func TestSkipsHeredocPayload(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041", "LEG042"}
	source := `cat <<'SCRIPT'

# Generated by codex.
SCRIPT
# Generated by codex.
`
	want := []expectedDiagnostic{
		{"LEG042", 5, 1, "Comment contains the prohibited attribution \"codex\"."},
		{"LEG041", 5, 1, "Comment does not match a configured matcher, prefix identifier, or suffix identifier."},
	}
	assertScan(t, source, config, want)
}

func TestSkipsTabStrippedHeredocPayload(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG041", "LEG042"}
	source := `cat <<-'SCRIPT'
# Generated by codex.
	SCRIPT
`
	assertScan(t, source, config, nil)
}

func TestUnclosedEscapedQuoteKeepsMultilineState(t *testing.T) {
	config := DefaultConfig()
	config.Select = []string{"LEG035"}
	source := `run() {
printf "escaped \" true
still literal false"
create_user true
}
`
	want := []expectedDiagnostic{
		{"LEG035", 4, 1, "Avoid boolean literal arguments. Name the option before passing it."},
	}
	assertScan(t, source, config, want)
}
