package integration

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yowainwright/shellcheck_legibility/internal/lint"
)

var binaryPath string
var workspaceRoot string

func TestMain(m *testing.M) {
	root, err := filepath.Abs("../..")
	if err != nil {
		panic(err)
	}
	binaryPath = filepath.Join(root, "bin", "shellcheck-legibility")
	workspaceRoot = filepath.Join(root, ".build")
	os.Exit(m.Run())
}

func runBinary(t *testing.T, engine string, args ...string) (string, int) {
	t.Helper()
	t.Setenv("SHELLCHECK_LEGIBILITY_ENGINE", engine)
	command := exec.Command(binaryPath, args...)
	output, err := command.CombinedOutput()
	if err == nil {
		return string(output), 0
	}
	if command.ProcessState == nil {
		t.Fatalf("run make build first: %v", err)
	}
	return string(output), command.ProcessState.ExitCode()
}

func scanFixture(t *testing.T, engine string, fixture ruleFixture) []lint.Diagnostic {
	t.Helper()
	output, status := runBinary(t, engine, "check", fixture.path, "--select", fixture.code, "--no-cache", "--output-format", "json")
	if status != 1 {
		t.Fatalf("%s engine exited %d: %s", engine, status, output)
	}
	var findings []lint.Diagnostic
	if err := json.Unmarshal([]byte(output), &findings); err != nil {
		t.Fatal(err)
	}
	return findings
}

type ruleFixture struct{ code, path, source string }

func TestEveryRuleMatchesBash(t *testing.T) {
	enterTestWorkspace(t)
	fixtures := append(controlFixtures(), shellFixtures()...)
	for _, fixture := range fixtures {
		t.Run(fixture.code, func(t *testing.T) { compareRule(t, fixture) })
	}
}

func controlFixtures() []ruleFixture {
	return []ruleFixture{
		{"LEG001", "example.sh", "build && test && package && publish && notify && finish\n"},
		{"LEG002", "example.sh", "if ready && online; then work; fi\n"},
		{"LEG003", "example.sh", "if a; then\nif b; then\nif c; then\nif d; then work; fi\nfi\nfi\nfi\n"},
		{"LEG005", "example.sh", "for a in one; do\nfor b in two; do work; done\ndone\n"},
		{"LEG009", "example.sh", "run() {\nif ready; then\nreturn\nelse\nwork\nfi\n}\n"},
		{"LEG010", "example.sh", "run() {\nif ready; then\nwork\nfi\n}\n"},
	}
}

func shellFixtures() []ruleFixture {
	return []ruleFixture{
		{"LEG016", "scripts/run.sh", "run() { :; }\n"},
		{"LEG017", "example.sh", "bash scripts/run.sh\n"},
		{"LEG024", "example.sh", "if [[ $mode == a || $mode == b || $mode == c ]]; then work; fi\n"},
		{"LEG025", "src/forms/button/other.sh", "run() { :; }\n"},
		{"LEG026", "mixed_Name.sh", "run() { :; }\n"},
		{"LEG034", "example.sh", "if [[ $mode == a ]]; then work\nelif [[ $mode == b ]]; then work\nelif [[ $mode == c ]]; then work\nfi\n"},
		{"LEG035", "example.sh", "create_user true\n"},
		{"LEG038", "example.sh", "run() {\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nwork\n}\n"},
		{"LEG039", "example.sh", "docker build .\n"},
		{"LEG040", "example.sh", "run() {\nlocal name=$1\n}\n"},
		{"LEG041", "example.sh", "# ordinary comment\n"},
		{"LEG042", "example.sh", "# Generated by Codex.\n"},
		{"LEG043", "example.sh", "# first comment\n# second comment\n"},
	}
}

func compareRule(t *testing.T, fixture ruleFixture) {
	writeRuleFixture(t, fixture)
	expected := scanFixture(t, "bash", fixture)
	actual := scanFixture(t, "", fixture)
	if len(expected) == 0 {
		t.Fatal("fixture did not exercise the rule")
	}
	compareRuleJSON(t, expected, actual)
}

func writeRuleFixture(t *testing.T, fixture ruleFixture) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(fixture.path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fixture.path, []byte(fixture.source), 0600); err != nil {
		t.Fatal(err)
	}
}

func compareRuleJSON(t *testing.T, expected, actual []lint.Diagnostic) {
	t.Helper()
	expectJSON, _ := json.Marshal(expected)
	actualJSON, _ := json.Marshal(actual)
	if string(expectJSON) != string(actualJSON) {
		t.Fatalf("expected %s\nactual   %s", expectJSON, actualJSON)
	}
}

func TestIncompleteShellKeepsFeedbackWithoutExecutingSource(t *testing.T) {
	enterTestWorkspace(t)
	source := "touch executed\nrun() { create_user true;\n"
	if err := os.WriteFile("incomplete.sh", []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	findings := scanFixture(t, "", ruleFixture{"LEG035", "incomplete.sh", source})
	if len(findings) != 1 || findings[0].Code != "LEG035" {
		t.Fatalf("findings: %+v", findings)
	}
	if _, err := os.Stat("executed"); !os.IsNotExist(err) {
		t.Fatal("scanned source was executed")
	}
}

func TestNativeEngineDoesNotRequireBash(t *testing.T) {
	enterTestWorkspace(t)
	writeRuleFixture(t, ruleFixture{path: "incomplete.sh", source: "run() { create_user true;\n"})
	t.Setenv("PATH", "")
	output, status := runBinary(t, "", "check", "incomplete.sh", "--select", "LEG035", "--no-cache")
	if status != 1 || !strings.Contains(output, "LEG035") {
		t.Fatalf("status %d: %s", status, output)
	}
	writeRuleFixture(t, ruleFixture{path: "unrecoverable.sh", source: "create_user true\nunexpected)\n"})
	writeRuleFixture(t, ruleFixture{path: "remaining.sh", source: "create_user true\n"})
	output, status = runBinary(t, "", "check", "unrecoverable.sh", "remaining.sh", "--select", "LEG035", "--no-cache")
	if status != 2 || strings.Count(output, "LEG035") != 2 || !strings.Contains(output, "unrecoverable.sh") || !strings.Contains(output, "remaining.sh") || strings.Contains(output, "Bash is required") {
		t.Fatalf("status %d: %s", status, output)
	}
}

func TestNativeScanDoesNotRequireBash(t *testing.T) {
	enterTestWorkspace(t)
	t.Setenv("PATH", "")
	fixture := ruleFixture{"LEG035", "example.sh", "create_user true\n"}
	writeRuleFixture(t, fixture)
	if findings := scanFixture(t, "", fixture); len(findings) != 1 {
		t.Fatalf("findings: %+v", findings)
	}
}

func TestMalformedSourceKeepsRuleFeedback(t *testing.T) {
	enterTestWorkspace(t)
	fixtures := []ruleFixture{
		{"LEG042", "example.sh", "value=\"$(\n  case \"$target\" in\n    x) # Generated by codex.\n"},
		{"LEG040", "example.sh", "deploy()\n{\nlocal target=\"$1\"\n"},
	}
	for _, fixture := range fixtures {
		t.Run(fixture.code, func(t *testing.T) { compareRule(t, fixture) })
	}
}

func enterTestWorkspace(t *testing.T) {
	t.Helper()
	if err := os.MkdirAll(workspaceRoot, 0755); err != nil {
		t.Fatal(err)
	}
	dir, err := os.MkdirTemp(workspaceRoot, "integration-")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.RemoveAll(dir) })
	t.Chdir(dir)
}
