name: Compatibility

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  compatibility:
    name: System Bash
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Test system Bash compatibility
        run: PATH=/usr/bin:/bin /bin/bash tests/unit/rules.bash
